# Generated by Django 5.1.4 on 2024-12-08 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipo', '0001_initial'),
        ('unidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('ano', models.DateField()),
                ('placa', models.CharField(max_length=10)),
                ('prefixo', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='tipo.tipo')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='veiculos', to='unidade.unidade')),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
