# Generated by Django 5.1.4 on 2024-12-08 17:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colete', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colete',
            name='genero',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colete',
            name='tamanho',
            field=models.CharField(default='M', max_length=5),
            preserve_default=False,
        ),
    ]
